In [421]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from astropy import units as u
from astropy import constants as const

In [422]:
# 2.1.1.3
df = pd.read_csv('solar_system.csv')
df

,Attribute,Mercury,Venus,Earth,Moon,Mars,Jupiter,Saturn,Uranus,Neptune,Pluto
0,Mass (10^24kg),0.330,4.87,5.97,0.073,0.642,1898,568,86.8,102,0.0130
1,Diameter (km),4879,12104,12756,3475,6792,142984,120536,51118,49528,2376
2,Density (kg/m^3),5429,5243,5514,3340,3934,1326,687,1270,1638,1850
3,Gravity (m/s^2),3.7,8.9,9.8,1.6,3.7,23.1,9.0,8.7,11.0,0.7
4,Escape Velocity (km/s),4.3,10.4,11.2,2.4,5.0,59.5,35.5,21.3,23.5,1.3
5,Rotation Period (hours),1407.6,-5832.5,23.9,655.7,24.6,9.9,10.7,-17.2,16.1,-153.3
6,Length of Day (hours),4222.6,2802.0,24.0,708.7,24.7,9.9,10.7,17.2,16.1,153.3
7,Distance from Sun (10^6 km),57.9,108.2,149.6,0.384,228.0,778.5,1432.0,2867.0,4515.0,5906.4
8,Perihelion (10^6 km),46.0,107.5,147.1,0.363,206.7,740.6,1357.6,2732.7,4471.1,4436.8
9,Aphelion (10^6 km),69.8,108.9,152.1,0.406,249.3,816.4,1506.5,3001.4,4558.9,7375.9
10,Orbital Period (days),88.0,224.7,365.2,27.3,687.0,4331,10747,30589,59800,90560
11,Orbital Velocity (km/s),47.4,35.0,29.8,1.0,24.1,13.1,9.7,6.8,5.4,4.7
12,Orbital Inclination (deg),7.0,3.4,0.0,5.1,1.8,1.3,2.5,0.8,1.8,17.2
13,Orbital Eccentricity,0.206,0.007,0.017,0.055,0.094,0.049,0.052,0.047,0.010,0.244
14,Obliquity to Orbit (deg),0.034,177.4,23.4,6.7,25.2,3.1,26.7,97.8,28.3,119.5
15,Mean Temperature (C),167,464,15,-20,-65,-110,-140,-195,-200,-225
16,Surface Pressure (bars),0,92,1,0,0.01,Unknown,Unknown,Unknown,Unknown,0.00001
17,Number of Moons,0,0,1,0,2,95,274,28,16,5
18,Ring System?,No,No,No,No,No,Yes,Yes,Yes,Yes,No
19,Global Magnetic Field?,Yes,No,Yes,No,No,Yes,Yes,Yes,Yes,Unknown

In [423]:
# 2.1.1.4
df1 = df.set_index("Attribute").T
df1.index.name = "Planet"
df1.reset_index(inplace=True)
df1.columns.name = None
df1

,Planet,Mass (10^24kg),Diameter (km),Density (kg/m^3),Gravity (m/s^2),Escape Velocity (km/s),Rotation Period (hours),Length of Day (hours),Distance from Sun (10^6 km),Perihelion (10^6 km),...,Orbital Period (days),Orbital Velocity (km/s),Orbital Inclination (deg),Orbital Eccentricity,Obliquity to Orbit (deg),Mean Temperature (C),Surface Pressure (bars),Number of Moons,Ring System?,Global Magnetic Field?
0,Mercury,0.330,4879,5429,3.7,4.3,1407.6,4222.6,57.9,46.0,...,88.0,47.4,7.0,0.206,0.034,167,0,0,No,Yes
1,Venus,4.87,12104,5243,8.9,10.4,-5832.5,2802.0,108.2,107.5,...,224.7,35.0,3.4,0.007,177.4,464,92,0,No,No
2,Earth,5.97,12756,5514,9.8,11.2,23.9,24.0,149.6,147.1,...,365.2,29.8,0.0,0.017,23.4,15,1,1,No,Yes
3,Moon,0.073,3475,3340,1.6,2.4,655.7,708.7,0.384,0.363,...,27.3,1.0,5.1,0.055,6.7,-20,0,0,No,No
4,Mars,0.642,6792,3934,3.7,5.0,24.6,24.7,228.0,206.7,...,687.0,24.1,1.8,0.094,25.2,-65,0.01,2,No,No
5,Jupiter,1898,142984,1326,23.1,59.5,9.9,9.9,778.5,740.6,...,4331,13.1,1.3,0.049,3.1,-110,Unknown,95,Yes,Yes
6,Saturn,568,120536,687,9.0,35.5,10.7,10.7,1432.0,1357.6,...,10747,9.7,2.5,0.052,26.7,-140,Unknown,274,Yes,Yes
7,Uranus,86.8,51118,1270,8.7,21.3,-17.2,17.2,2867.0,2732.7,...,30589,6.8,0.8,0.047,97.8,-195,Unknown,28,Yes,Yes
8,Neptune,102,49528,1638,11.0,23.5,16.1,16.1,4515.0,4471.1,...,59800,5.4,1.8,0.010,28.3,-200,Unknown,16,Yes,Yes
9,Pluto,0.0130,2376,1850,0.7,1.3,-153.3,153.3,5906.4,4436.8,...,90560,4.7,17.2,0.244,119.5,-225,0.00001,5,No,Unknown

In [424]:
# 2.1.1.5
# a.
print(df.shape)
print(df1.shape)
# b.
# 20 rows, 11 columns before. 10 rows, 21 columns afterward.
# c.
# The first line moves the attributes to the columns and the planets to the rows.
# The second line names the index numbers the name of each planet.
# The third line moves the planet names to its own column.
# The fourth line removes the name 'Atributes' from the index column.
# d.
# The first column of the new dataframe is the name of the planets versus the original dataframe that had the planet names as the name of each 
# column.
# e.
df1.columns
# f.
# 16 columns have units
# Columns with units: Mass, Diameter, Density, Gravity, Escape Velocity, Rotation Period, 
# Length of Day, Distance from Sun, Perihelion, Aphelion, Orbital Period, 
# Orbital Velocity, Orbital Inclination, Obliquity to Orbit, Mean Temperature, and 
# Surface Pressure.
# 4 columns do not have units
# Columns without units: Orbital Eccentricity, 
# Number of Moons, Ring System?, and Global Magnetic Field?
# g.
df1

(20, 11)
(10, 21)

,Planet,Mass (10^24kg),Diameter (km),Density (kg/m^3),Gravity (m/s^2),Escape Velocity (km/s),Rotation Period (hours),Length of Day (hours),Distance from Sun (10^6 km),Perihelion (10^6 km),...,Orbital Period (days),Orbital Velocity (km/s),Orbital Inclination (deg),Orbital Eccentricity,Obliquity to Orbit (deg),Mean Temperature (C),Surface Pressure (bars),Number of Moons,Ring System?,Global Magnetic Field?
0,Mercury,0.330,4879,5429,3.7,4.3,1407.6,4222.6,57.9,46.0,...,88.0,47.4,7.0,0.206,0.034,167,0,0,No,Yes
1,Venus,4.87,12104,5243,8.9,10.4,-5832.5,2802.0,108.2,107.5,...,224.7,35.0,3.4,0.007,177.4,464,92,0,No,No
2,Earth,5.97,12756,5514,9.8,11.2,23.9,24.0,149.6,147.1,...,365.2,29.8,0.0,0.017,23.4,15,1,1,No,Yes
3,Moon,0.073,3475,3340,1.6,2.4,655.7,708.7,0.384,0.363,...,27.3,1.0,5.1,0.055,6.7,-20,0,0,No,No
4,Mars,0.642,6792,3934,3.7,5.0,24.6,24.7,228.0,206.7,...,687.0,24.1,1.8,0.094,25.2,-65,0.01,2,No,No
5,Jupiter,1898,142984,1326,23.1,59.5,9.9,9.9,778.5,740.6,...,4331,13.1,1.3,0.049,3.1,-110,Unknown,95,Yes,Yes
6,Saturn,568,120536,687,9.0,35.5,10.7,10.7,1432.0,1357.6,...,10747,9.7,2.5,0.052,26.7,-140,Unknown,274,Yes,Yes
7,Uranus,86.8,51118,1270,8.7,21.3,-17.2,17.2,2867.0,2732.7,...,30589,6.8,0.8,0.047,97.8,-195,Unknown,28,Yes,Yes
8,Neptune,102,49528,1638,11.0,23.5,16.1,16.1,4515.0,4471.1,...,59800,5.4,1.8,0.010,28.3,-200,Unknown,16,Yes,Yes
9,Pluto,0.0130,2376,1850,0.7,1.3,-153.3,153.3,5906.4,4436.8,...,90560,4.7,17.2,0.244,119.5,-225,0.00001,5,No,Unknown

In [425]:
# 2.1.2 Investigate Data Types
# 2.1.2.1
df1.dtypes

Planet                         object
Mass (10^24kg)                 object
Diameter (km)                  object
Density (kg/m^3)               object
Gravity (m/s^2)                object
Escape Velocity (km/s)         object
Rotation Period (hours)        object
Length of Day (hours)          object
Distance from Sun (10^6 km)    object
Perihelion (10^6 km)           object
Aphelion (10^6 km)             object
Orbital Period (days)          object
Orbital Velocity (km/s)        object
Orbital Inclination (deg)      object
Orbital Eccentricity           object
Obliquity to Orbit (deg)       object
Mean Temperature (C)           object
Surface Pressure (bars)        object
Number of Moons                object
Ring System?                   object
Global Magnetic Field?         object
dtype: object

In [426]:
# 2.1.2.2
for col in df1:
        print(df1[col].apply(type))

0    <class 'str'>
1    <class 'str'>
2    <class 'str'>
3    <class 'str'>
4    <class 'str'>
5    <class 'str'>
6    <class 'str'>
7    <class 'str'>
8    <class 'str'>
9    <class 'str'>
Name: Planet, dtype: object
0    <class 'str'>
1    <class 'str'>
2    <class 'str'>
3    <class 'str'>
4    <class 'str'>
5    <class 'str'>
6    <class 'str'>
7    <class 'str'>
8    <class 'str'>
9    <class 'str'>
Name: Mass (10^24kg), dtype: object
0    <class 'str'>
1    <class 'str'>
2    <class 'str'>
3    <class 'str'>
4    <class 'str'>
5    <class 'str'>
6    <class 'str'>
7    <class 'str'>
8    <class 'str'>
9    <class 'str'>
Name: Diameter (km), dtype: object
0    <class 'str'>
1    <class 'str'>
2    <class 'str'>
3    <class 'str'>
4    <class 'str'>
5    <class 'str'>
6    <class 'str'>
7    <class 'str'>
8    <class 'str'>
9    <class 'str'>
Name: Density (kg/m^3), dtype: object
0    <class 'str'>
1    <class 'str'>
2    <class 'str'>
3    <class 'str'>
4    <class 'str'>
5    <class 'str'>
6    <class 'str'>
7    <class 'str'>
8    <class 'str'>
9    <class 'str'>
Name: Gravity (m/s^2), dtype: object
0    <class 'str'>
1    <class 'str'>
2    <class 'str'>
3    <class 'str'>
4    <class 'str'>
5    <class 'str'>
6    <class 'str'>
7    <class 'str'>
8    <class 'str'>
9    <class 'str'>
Name: Escape Velocity (km/s), dtype: object
0    <class 'str'>
1    <class 'str'>
2    <class 'str'>
3    <class 'str'>
4    <class 'str'>
5    <class 'str'>
6    <class 'str'>
7    <class 'str'>
8    <class 'str'>
9    <class 'str'>
Name: Rotation Period (hours), dtype: object
0    <class 'str'>
1    <class 'str'>
2    <class 'str'>
3    <class 'str'>
4    <class 'str'>
5    <class 'str'>
6    <class 'str'>
7    <class 'str'>
8    <class 'str'>
9    <class 'str'>
Name: Length of Day (hours), dtype: object
0    <class 'str'>
1    <class 'str'>
2    <class 'str'>
3    <class 'str'>
4    <class 'str'>
5    <class 'str'>
6    <class 'str'>
7    <class 'str'>
8    <class 'str'>
9    <class 'str'>
Name: Distance from Sun (10^6 km), dtype: object
0    <class 'str'>
1    <class 'str'>
2    <class 'str'>
3    <class 'str'>
4    <class 'str'>
5    <class 'str'>
6    <class 'str'>
7    <class 'str'>
8    <class 'str'>
9    <class 'str'>
Name: Perihelion (10^6 km), dtype: object
0    <class 'str'>
1    <class 'str'>
2    <class 'str'>
3    <class 'str'>
4    <class 'str'>
5    <class 'str'>
6    <class 'str'>
7    <class 'str'>
8    <class 'str'>
9    <class 'str'>
Name: Aphelion (10^6 km), dtype: object
0    <class 'str'>
1    <class 'str'>
2    <class 'str'>
3    <class 'str'>
4    <class 'str'>
5    <class 'str'>
6    <class 'str'>
7    <class 'str'>
8    <class 'str'>
9    <class 'str'>
Name: Orbital Period (days), dtype: object
0    <class 'str'>
1    <class 'str'>
2    <class 'str'>
3    <class 'str'>
4    <class 'str'>
5    <class 'str'>
6    <class 'str'>
7    <class 'str'>
8    <class 'str'>
9    <class 'str'>
Name: Orbital Velocity (km/s), dtype: object
0    <class 'str'>
1    <class 'str'>
2    <class 'str'>
3    <class 'str'>
4    <class 'str'>
5    <class 'str'>
6    <class 'str'>
7    <class 'str'>
8    <class 'str'>
9    <class 'str'>
Name: Orbital Inclination (deg), dtype: object
0    <class 'str'>
1    <class 'str'>
2    <class 'str'>
3    <class 'str'>
4    <class 'str'>
5    <class 'str'>
6    <class 'str'>
7    <class 'str'>
8    <class 'str'>
9    <class 'str'>
Name: Orbital Eccentricity, dtype: object
0    <class 'str'>
1    <class 'str'>
2    <class 'str'>
3    <class 'str'>
4    <class 'str'>
5    <class 'str'>
6    <class 'str'>
7    <class 'str'>
8    <class 'str'>
9    <class 'str'>
Name: Obliquity to Orbit (deg), dtype: object
0    <class 'str'>
1    <class 'str'>
2    <class 'str'>
3    <class 'str'>
4    <class 'str'>
5    <class 'str'>
6    <class 'str'>
7    <class 'str'>
8    <class 'str'>
9    <class 'str'>
Name: Mean Temperature (C), dtype: object
0    <class 'str'>
1    <class 'str'>
2    <class 'str'>
3    <class 'str'>
4    <class 'str'>
5    <class 'str'>
6    <class 'str'>
7    <class 'str'>
8    <class 'str'>
9    <class 'str'>
Name: Surface Pressure (bars), dtype: object
0    <class 'str'>
1    <class 'str'>
2    <class 'str'>
3    <class 'str'>
4    <class 'str'>
5    <class 'str'>
6    <class 'str'>
7    <class 'str'>
8    <class 'str'>
9    <class 'str'>
Name: Number of Moons, dtype: object
0    <class 'str'>
1    <class 'str'>
2    <class 'str'>
3    <class 'str'>
4    <class 'str'>
5    <class 'str'>
6    <class 'str'>
7    <class 'str'>
8    <class 'str'>
9    <class 'str'>
Name: Ring System?, dtype: object
0    <class 'str'>
1    <class 'str'>
2    <class 'str'>
3    <class 'str'>
4    <class 'str'>
5    <class 'str'>
6    <class 'str'>
7    <class 'str'>
8    <class 'str'>
9    <class 'str'>
Name: Global Magnetic Field?, dtype: object

In [427]:
# 2.1.2.3
# a.
# Every value is a string
# b.
# By storing numbers as strings, we can not apply mathematical functions to the data.

In [428]:
# 2.1.3 Convert Strings to Numbers
# 2.1.3.1
number_columns = ['Mass (10^24kg)', 'Diameter (km)', 'Density (kg/m^3)',
       'Gravity (m/s^2)', 'Escape Velocity (km/s)', 'Rotation Period (hours)',
       'Length of Day (hours)', 'Distance from Sun (10^6 km)',
       'Perihelion (10^6 km)', 'Aphelion (10^6 km)', 'Orbital Period (days)',
       'Orbital Velocity (km/s)', 'Orbital Inclination (deg)',
       'Orbital Eccentricity', 'Obliquity to Orbit (deg)',
       'Mean Temperature (C)', 'Surface Pressure (bars)', 'Number of Moons',]
for col in number_columns:
    df1[col] = pd.to_numeric(df1[col], errors="coerce")

In [429]:
# 2.1.3.2
df1.dtypes

Planet                          object
Mass (10^24kg)                 float64
Diameter (km)                    int64
Density (kg/m^3)                 int64
Gravity (m/s^2)                float64
Escape Velocity (km/s)         float64
Rotation Period (hours)        float64
Length of Day (hours)          float64
Distance from Sun (10^6 km)    float64
Perihelion (10^6 km)           float64
Aphelion (10^6 km)             float64
Orbital Period (days)          float64
Orbital Velocity (km/s)        float64
Orbital Inclination (deg)      float64
Orbital Eccentricity           float64
Obliquity to Orbit (deg)       float64
Mean Temperature (C)             int64
Surface Pressure (bars)        float64
Number of Moons                  int64
Ring System?                    object
Global Magnetic Field?          object
dtype: object

In [430]:
# 2.1.3.3
# a.
# objects, floats, and integers.
# b.
# An object is anything, float string, etc. A float is a number with a decimal -- a 
# not whole number. An integer is a whole number
# c.
# The columns Planet, Ring System?, and Global Magnetic Field? are still objects becasue 
# we did not change their datatype due to the fact that they are words and no numbers.

In [431]:
# 2.2 Apply Astropy Units
# 2.2.1
def attach_units(old_col):
    if old_col == 'Mass (10^24kg)':
        new_values = []
        new_col = 'Mass (kg)'
        for val in df1[old_col]:
            new_values.append(val * 1**24 * u.kg)
        df1[old_col] = new_values
        df1.rename(columns = {old_col: new_col}, inplace = True)
    elif old_col == 'Diameter (km)':
        new_values = []
        for val in df1[old_col]:
            new_values.append(val * u.km)
        df1[old_col] = new_values
    elif old_col == 'Density (kg/m^3)':
        new_values = []
        for val in df1[old_col]:
            new_values.append(val * u.kg / (u.m)**3)
        df1[old_col] = new_values
    elif old_col == 'Gravity (m/s^2)':
        new_values = []
        for val in df1[old_col]:
            new_values.append(val * u.m / (u.s)**2)
        df1[old_col] = new_values
    elif old_col == 'Escape Velocity (km/s)':
        new_values = []
        for val in df1[old_col]:
            new_values.append(val * u.km / u.s)
        df1[old_col] = new_values
    elif old_col == 'Rotation Period (hours)':
        new_values = []
        for val in df1[old_col]:
            new_values.append(val * u.hour)
        df1[old_col] = new_values
    elif old_col == 'Length of Day (hours)':
        new_values = []
        for val in df1[old_col]:
            new_values.append(val * u.hour)
        df1[old_col] = new_values
    elif old_col == 'Distance from Sun (10^6 km)':
        new_values = []
        new_col = 'Distance from Sun (km)'
        for val in df1[old_col]:
            new_values.append(val * 1**6 * u.km)     
        df1[old_col] = new_values
        df1.rename(columns = {old_col: new_col}, inplace = True)
        df1[old_col] = new_values
    elif old_col == 'Perihelion (10^6 km)':
        new_values = []
        new_col = 'Perihelion (km)'
        for val in df1[old_col]:
            new_values.append(val * 1**6 * u.km)     
        df1[old_col] = new_values
        df1.rename(columns = {old_col: new_col}, inplace = True)
        df1[old_col] = new_values
    elif old_col == 'Aphelion (10^6 km)':
        new_values = []
        new_col = 'Aphelion (km)'
        for val in df1[old_col]:
            new_values.append(val * 1**6 * u.km)     
        df1[old_col] = new_values
        df1.rename(columns = {old_col: new_col}, inplace = True)
        df1[old_col] = new_values
    elif old_col == 'Orbital Period (days)':
        new_values = []
        for val in df1[old_col]:
            new_values.append(val * u.d)
        df1[old_col] = new_values
    elif old_col == 'Orbital Velocity (km/s)':
        new_values = []
        for val in df1[old_col]:
            new_values.append(val * u.km / u.s)
        df1[old_col] = new_values
    elif old_col == 'Orbital Inclination (deg)':
        new_values = []
        for val in df1[old_col]:
            new_values.append(val * u.deg)
        df1[old_col] = new_values
    elif old_col == 'Obliquity to Orbit (deg)':
        new_values = []
        for val in df1[old_col]:
            new_values.append(val * u.deg)
        df1[old_col] = new_values
    elif old_col == 'Mean Temperature (C)':
        new_values = []
        for val in df1[old_col]:
            new_values.append(val * u.deg_C)
        df1[old_col] = new_values
    elif old_col == 'Surface Pressure (bars)':
        new_values = []
        for val in df1[old_col]:
            new_values.append(val * u.bar)
        df1[old_col] = new_values



attach_units('Mass (10^24kg)')
attach_units('Diameter (km)')
attach_units('Density (kg/m^3)')
attach_units('Gravity (m/s^2)')
attach_units('Escape Velocity (km/s)')
attach_units('Rotation Period (hours)')
attach_units('Length of Day (hours)')
attach_units('Distance from Sun (10^6 km)')
attach_units('Perihelion (10^6 km)')
attach_units('Aphelion (10^6 km)')
attach_units('Orbital Period (days)')
attach_units('Orbital Velocity (km/s)')
attach_units('Orbital Inclination (deg)')
attach_units('Obliquity to Orbit (deg)')
attach_units('Mean Temperature (C)')
attach_units('Surface Pressure (bars)')
df1['Density (kg/m^3)']

0    5429.0 kg / m3
1    5243.0 kg / m3
2    5514.0 kg / m3
3    3340.0 kg / m3
4    3934.0 kg / m3
5    1326.0 kg / m3
6     687.0 kg / m3
7    1270.0 kg / m3
8    1638.0 kg / m3
9    1850.0 kg / m3
Name: Density (kg/m^3), dtype: object

In [432]:
# 2.3 Data Analysis
# 2.3.1 Semi-Major Axis

perihelion = df1['Perihelion (km)']
aphelion = df1['Aphelion (km)']

semi_major_axis = (perihelion + aphelion) / 2
semi_major_axis

df1.insert(11, 'Semi Major Axis (km)', semi_major_axis)

In [433]:
# 2.3.1 Continued
df1.columns
df1['Semi Major Axis (km)']
# Units!

0       57.9 km
1      108.2 km
2      149.6 km
3     0.3845 km
4      228.0 km
5      778.5 km
6    1432.05 km
7    2867.05 km
8     4515.0 km
9    5906.35 km
Name: Semi Major Axis (km), dtype: object

In [434]:
# 2.3.2 Convert Orbital Period to Years
df1.rename(columns = {'Orbital Period (days)': 'Orbital Period (years)'}, inplace = True)
converted_values = []
for value in df1['Orbital Period (years)']:
    converted_values.append(value.to(u.yr))
    
df1['Orbital Period (years)'] = converted_values

print(df1.columns)
print(df1['Orbital Period (years)'])
print(f"{df1['Orbital Period (years)'].iloc[1]:.4f}")

Index(['Planet', 'Mass (kg)', 'Diameter (km)', 'Density (kg/m^3)',
       'Gravity (m/s^2)', 'Escape Velocity (km/s)', 'Rotation Period (hours)',
       'Length of Day (hours)', 'Distance from Sun (km)', 'Perihelion (km)',
       'Aphelion (km)', 'Semi Major Axis (km)', 'Orbital Period (years)',
       'Orbital Velocity (km/s)', 'Orbital Inclination (deg)',
       'Orbital Eccentricity', 'Obliquity to Orbit (deg)',
       'Mean Temperature (C)', 'Surface Pressure (bars)', 'Number of Moons',
       'Ring System?', 'Global Magnetic Field?', 'Distance from Sun (10^6 km)',
       'Perihelion (10^6 km)', 'Aphelion (10^6 km)'],
      dtype='object')
0    0.24093086926762491 yr
1     0.6151950718685831 yr
2     0.9998631074606433 yr
3    0.07474332648870637 yr
4     1.8809034907597535 yr
5      11.85763175906913 yr
6     29.423682409308693 yr
7      83.74811772758385 yr
8     163.72347707049965 yr
9     247.93976728268308 yr
Name: Orbital Period (years), dtype: object
0.6152 yr

In [436]:
# 2.3.3 Convert Distance Columns (km --> AU):
# 1 AU is equal to the average distance between the Sun and the Earth
print(const.au)
(const.au).to(u.km) # 1.4959787 * 10^8 km in 1 AU


distance_columns = ['Diameter (km)', 'Distance from Sun (km)', 
                    'Perihelion (km)', 'Aphelion (km)']
for column in distance_columns:
    if column == 'Diameter (km)':
        new_values = []
        new_col = 'Diameter (AU)'
        for val in df1[column]:
            new_values.append(val.to(u.au))
        df1[column] = new_values
        df1.rename(columns = {column: new_col}, inplace = True)
    elif column == 'Distance from Sun (km)':
        new_values = []
        new_col = 'Distance from Sun (AU)'
        for val in df1[column]:
            new_values.append(val.to(u.au))
        df1[column] = new_values
        df1.rename(columns = {column: new_col}, inplace = True)
    elif column == 'Perihelion (km)':
        new_values = []
        new_col = 'Perihelion (AU)'
        for val in df1[column]:
            new_values.append(val.to(u.au))
        df1[column] = new_values
        df1.rename(columns = {column: new_col}, inplace = True)
    elif column == 'Aphelion (km)':
        new_values = []
        new_col = 'Aphelion (AU)'
        for val in df1[column]:
            new_values.append(val.to(u.au))
        df1[column] = new_values
        df1.rename(columns = {column: new_col}, inplace = True)

  Name   = Astronomical Unit
  Value  = 149597870700.0
  Uncertainty  = 0.0
  Unit  = m
  Reference = IAU 2012 Resolution B2

In [440]:
print(df1['Diameter (AU)'].iloc[1])
print(df1['Distance from Sun (AU)'].iloc[1])
print(df1['Perihelion (AU)'].iloc[1])
print(df1['Aphelion (AU)'].iloc[1])

8.091024252793726e-05 AU
7.232723266294459e-07 AU
7.185931156438579e-07 AU
7.279515376150337e-07 AU

In [441]:
# I dont have time for the bonus :( I'll take a look later

In [442]:
# 2.4 Save Your Results
df1.to_csv('units.csv', index=False)

In [ ]:
# 3 FITS Files